### ISSUE TITLE
Documentation outdated or incomplete

### ISSUE THREAD

**Issue by dpoerschke** [HCL-TECH-SOFTWARE/Domino-rest-api#1]
Hi, could you please update "How to configure keycloak" (the screenshots show the old gui of KeyCloak (version 19 and older), the current version is 21.0.1 and some configuration items are not found or in a different place in the gui)? I assume you have to set up KeyCloak as identity provider before as described in "how to configure an identity provider", is that correct? Where do you get the 10-jwt.pubkey mentioned in "how to configure an identity provider"? It seems like there are some steps missing in the documentation. Even after several hours of searching and trying around, I still haven't managed to get KeyCloak to work with Keep :-/
It would be great if you could complete the documentation. Many thanks for your effort!

**Comment by digihernandez** [comment]
the documentation for Keycloak has been updated. Kindly see.
