### ISSUE TITLE
Downloads not available for Lab 06 and Lab 08

### ISSUE THREAD

**Issue by paulswithers** [HCL-TECH-SOFTWARE/Domino-rest-api#4]
https://opensource.hcltechsw.com/Domino-rest-api/tutorial/walkthrough/lab-06.html, no NodeJSExample.zip
https://opensource.hcltechsw.com/Domino-rest-api/tutorial/walkthrough/lab-08.html, no DominoJavaCmdLine.zip

**Comment by digihernandez** [comment]
Acknowledge the receipt of your issue Paul.  I will review it and reply to you with the update ASAP.

**Comment by digihernandez** [comment]
the documentation has been updated. Sorry for the delay of reply.
